GET http://localhost:3003/api/blogs

### 
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
  "title": "Titulo 2",
  "author": "Autor",
  "url": "url",
  "likes": 11
}

### Unknow endpoint
GET http://localhost:3003/api

### Delete
DELETE http://localhost:3003/api/blogs/6669fdd2f79ccc3236295f51

### update likes
PUT http://localhost:3003/api/blogs/6669fde0f79ccc3236295f53 HTTP/1.1
content-type: application/json

{
  "likes": 999
}


### 
GET http://localhost:3003/api/users

### 
POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
  "username": "nachitofj",
  "password": "passwordNachitofj",
  "name": "Ignacio Fernández"
}