GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
  "title": "Titulo",
  "author": "Autor",
  "url": "url",
  "likes": 11
}

### Unknow endpoint
GET http://localhost:3003/api